### ISSUE TITLE
Error in change_e when running outside growth routine.

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/estgrowth#1]
Christine there is an error in your estimation routine when it is run inside the package. Maybe you can work on finding out what this is? If you run the code in the `runEstGrowth.R` file you can run a single scenario and the error will come up. Then if you change code somewhere just run `devtools::load_all("c:/locationofpackage")` and then `unlink("scenario", recursive = TRUE)` and run the scenario again. I have been adding `browser()` at points in the code to make things easier to debug. Let me know if there is something I can help with.

**Comment by cstawitz** [comment]
Kelli, did you change the runestgrowth file over the weekend? It was
working for me on Friday, but now I get this error: Error in file(file,
"rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file
'C:/Users/Christine/Documents/GitHub/estgrowth/casefiles/bin0-cod.txt': No
such file or directory

On Sun, Oct 19, 2014 at 7:57 AM, Kelli Johnson notifications@github.com
wrote:

> Assigned #1 https://github.com/ss3sim/estgrowth/issues/1 to @cstawitz
> https://github.com/cstawitz.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ss3sim/estgrowth/issues/1#event-180521096.

## 

Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by seananderson** [comment]
I changed the file name from `B..txt` to `bin...txt` to match the other functions. See here: https://github.com/ss3sim/ss3sim/issues/167#issuecomment-59639214

I changed the files in the ss3sim package, but didn't touch those in the estgrowth repository. Try renaming the `B` files to `bin` files.

**Comment by cstawitz** [comment]
Thanks Sean - there actually aren't any "B" files in the estgrowth
casefiles repository either. I was able to get it working by just removing
the "B" case entirely - hopefully that doesn't invalidate the test.

On Sun, Oct 19, 2014 at 6:01 PM, Sean Anderson notifications@github.com
wrote:

> I changed the file name from B..txt to bin...txt to match the other
> functions. See here: ss3sim/ss3sim#167 (comment)
> https://github.com/ss3sim/ss3sim/issues/167#issuecomment-59639214
> 
> I changed the files in the ss3sim package, but didn't touch those in the
> estgrowth repository. Try renaming the B files to bin files.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ss3sim/estgrowth/issues/1#issuecomment-59673437.

## 

Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by seananderson** [comment]
The problem could just be that there are no '`bin` case files in your folder. Since the `change_bin` function is now merged into the same branch, that function now exists and expects to get input if the `B` case letter is specified.

**Comment by cstawitz** [comment]
OK - I am still new to this ss3sim thing. What case letters/files are
required to successfully run the model? Can I just remove the "B" case or
is a bin case file required for the model to run?

On Sun, Oct 19, 2014 at 6:37 PM, Sean Anderson notifications@github.com
wrote:

> The problem could just be that there are no 'bin case files in your
> folder. Since the change_bin function is now merged into the same branch,
> that function now exists and expects to get input if the B case letter is
> specified.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ss3sim/estgrowth/issues/1#issuecomment-59674846.

## 

Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by cstawitz** [comment]
OK, I added in the bin0 file from the main ss3sim casefiles folder and was
able to run the om and em successfully. Thanks for your help!

On Sun, Oct 19, 2014 at 6:41 PM, Christine Stawitz cstawitz@uw.edu wrote:

> OK - I am still new to this ss3sim thing. What case letters/files are
> required to successfully run the model? Can I just remove the "B" case or
> is a bin case file required for the model to run?
> 
> On Sun, Oct 19, 2014 at 6:37 PM, Sean Anderson notifications@github.com
> wrote:
> 
> > The problem could just be that there are no 'bin case files in your
> > folder. Since the change_bin function is now merged into the same
> > branch, that function now exists and expects to get input if the B case
> > letter is specified.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ss3sim/estgrowth/issues/1#issuecomment-59674846.
> 
> ## 
> 
> Christine Stawitz
> Quantitative Ecology and Resource Management
> Box 355020
> University of Washington
> Seattle, WA 98195
> cstawitz@uw.edu
> 
> http://students.washington.edu/cstawitz/

## 

Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by kellijohnson-NOAA** [comment]
Sorry i was MIA. I am partially back for a bit. Christine, the B case is 
not needed for all runs, just for when you want additional data, such as 
mean size at age or conditional length at age.

**Comment by cstawitz** [comment]
I just realized this issue is still open - I think it is fixed now?
